# Deploy to GitHub Pages: Because Why Host Locally When You Can Overcomplicate Everything?
#
# This workflow will take our 500MB of dependencies and somehow turn them into
# a static website. Modern technology is truly a marvel.

name: 'Deploy TOTP Playground to GitHub Pages (Probably)'

on:
  push:
    branches: ['main']
  # Manual trigger for when things inevitably break
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Build job - Where the magic (and tears) happen
  build:
    name: 'Build (And Pray It Works)'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get the code (revolutionary concept)
      - name: 'Checkout code (fetch the chaos)'
        uses: actions/checkout@v4

      # Step 2: Setup Node.js (because everything needs Node now)
      - name: 'Setup Node.js (summon the JavaScript gods)'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Step 3: Install dependencies (prepare for disappointment)
      - name: 'Install dependencies (download the internet)'
        run: |
          npm ci
          # Watch as GitHub's servers weep at our node_modules size

      # Step 4: Build the project (the moment of truth)
      - name: 'Build project (compile 6 numbers into enterprise software)'
        run: |
          npm run build
          # If this fails, it's probably because we looked at JavaScript wrong

      # Step 5: Setup GitHub Pages (because static hosting is apparently complex now)
      - name: 'Setup Pages (configure the deployment target)'
        uses: actions/configure-pages@v5

      # Step 6: Upload the built site
      - name: 'Upload artifact (package our beautiful creation)'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deploy job - The final frontier
  deploy:
    name: 'Deploy (Send It Into The Void)'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Deploy to GitHub Pages (cross your fingers)'
        id: deployment
        uses: actions/deploy-pages@v4

      # Optional: Celebrate if we got this far
      - name: 'Celebrate (or mourn) deployment'
        run: |
          echo "🎉 Deployment complete! Your TOTP playground is now live at:"
          echo "${{ steps.deployment.outputs.page_url }}"
          echo ""
          echo "If it's broken, remember: it worked on our machine! 🤷"
          echo "For support, please submit your complaints to /dev/null"
